# 주인공 — 인간 몸체 + 직업 킷 + HELD(손에 든 것).
# 배치: 0~3 머리/장비 · 4~6 얼굴 · 7 목 · 8~15 몸
#   눈: 앞뒤는 5행의 5·6과 9·10열, 옆은 5행의 8·9열
#   투구는 머리(4~11열)보다 한 칸 넓은 3~12열
# 무기는 여기 없다 — HELD 층이고 뒤를 볼 때는 몸 뒤에 그려진다.
GRIDS = {}

GRIDS['human'] = {
 'down': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '....1nNMMNn1....',
    '....0haaaah0....',
    '....0wkaakw0....',
    '....0HhaahH0....',
    '.....00hh00.....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDDDDDDDDX...',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '....1nNMMNNn....',
    '....1nhaaaa0....',
    '....1nhhwka0....',
    '....1nHhaah0....',
    '.....00hhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNX..',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDDDDDDDDX...',
    '....XDDDD1......',
    '....1nnnn1......',
 ]],
 'up': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '....1nNMMNn1....',
    '....1nNNNNn1....',
    '....1nNNNNn1....',
    '....1nnNNnn1....',
    '.....00hh00.....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDDDDDDDDX...',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
}

GRIDS['warrior'] = {
 'down': [raw(l) for l in [
    '.....222222.....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SS2222SS2...',
    '...2S......S2...',
    '...2S......S2...',
    '...2SS....SS2...',
    '....22222222....',
    '..2sSSSSSSSSs2..',
    '.2Ss2ssssss2sS2.',
    '.2Ss2sdddds2sS2.',
    '..222sdssds222..',
    '....2sdssds2....',
    '....2ddyydd2....',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '.....222222.....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSS22...',
    '...2SSSSS22.....',
    '...2SSSS2.......',
    '...2SSS2........',
    '....222222......',
    '..2sSSSSSSSs2...',
    '..2Ss2ssssss2...',
    '..2Ss2sdddds2...',
    '...222sdssds2...',
    '.....2sdssds2...',
    '.....2ddyyd2....',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '.....222222.....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2dSSSSSSd2...',
    '....22222222....',
    '..2sSSSSSSSSs2..',
    '.2Ss2ssssss2sS2.',
    '.2Ss2ssssss2sS2.',
    '..222ssssss222..',
    '....2ssssss2....',
    '....2dddddd2....',
    '................',
    '................',
 ]],
}

GRIDS['mage'] = {
 'down': [raw(l) for l in [
    '......6666......',
    '.....6bBBb6.....',
    '....6bBBBBb6....',
    '.663yyyyyyyy366.',
    '................',
    '................',
    '................',
    '................',
    '...6bBBBBBBb6...',
    '..6CCCCCCCCCC6..',
    '.6DCCCCCCCCCCD6.',
    '.63yyyyyyyyyy36.',
    '6DCCCCCCCCCCCCD6',
    '6DCCCCCCCCCCCCD6',
    '6DCCCCCCCCCCCCD6',
    '66CCCCCCCCCCCC66',
 ]],
 'side': [raw(l) for l in [
    '......6666......',
    '.....6bBBb6.....',
    '....6bBBBBb6....',
    '.663yyyyyyyy366.',
    '................',
    '................',
    '................',
    '................',
    '...6bBBBBBBb6...',
    '..6CCCCCCCCCC6..',
    '.6DCCCCCCCCCCD6.',
    '.63yyyyyyyyyy36.',
    '6DCCCCCCCCCCCCD6',
    '6DCCCCCCCCCCCCD6',
    '6DCCCCCCCCCCCCD6',
    '66CCCCCCCCCCCC66',
 ]],
 'up': [raw(l) for l in [
    '......6666......',
    '.....6bBBb6.....',
    '....6bBBBBb6....',
    '.663yyyyyyyy366.',
    '................',
    '................',
    '................',
    '................',
    '...6bBBBBBBb6...',
    '..6CCCCCCCCCC6..',
    '.6DCCCCCCCCCCD6.',
    '.6DDDDDDDDDDDD6.',
    '6DCCCCCCCCCCCCD6',
    '6DCCCCCCCCCCCCD6',
    '6DCCCCCCCCCCCCD6',
    '66CCCCCCCCCCCC66',
 ]],
}

GRIDS['priest'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..9CC3yyyy3CC9..',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9CDDDCCCCDDDC9.',
    '99CCCCCCCCCCCC99',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...9CC3yyCC9....',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9CDDDDDDDDC9..',
    '..99CCCCCCCC99..',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..9CCCCCCCCCC9..',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDDCCCCDDDC9.',
    '99CCCCCCCCCCCC99',
 ]],
}

GRIDS['rogue'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddk...',
    '.kCDDCCCCCCDD...',
    '.kCDDCCCCCCDD...',
    '..k1nNNNNNNn1...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddk...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk...',
    '..k1nNNNNNn1k...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddd...',
    '.kCDDCCCCCCDD...',
    '.kCDDCCCCCCDD...',
    '..k1nNNNNNNn1...',
    '..kCDDCCCCDDC...',
    '..kCDDCCCCDDC...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
}

GRIDS['ranger'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '............e...',
    '...51nNNNNn15...',
    '................',
    '................',
    '................',
    '................',
    '...eeeeeeee5....',
    '...DDCCCCDDC5...',
    '...DDCCCCDDC5...',
    '...1nNNNNn15....',
    '...CDDCCDDC5....',
    '...CDDCCDDC5....',
    '...5DDDDDD5.....',
    '...55555555.....',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '...e............',
    '...51nNNNNn15...',
    '................',
    '................',
    '................',
    '................',
    '...5eeeeeeee5...',
    '...5CDDCCCCDD...',
    '...5CDDCCCCDD...',
    '....51nNNNNn1...',
    '....5CDDCCDDC...',
    '....5CDDCCDDC...',
    '.....5DDDDDD5...',
    '.....55555555...',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '............e...',
    '...51nNNNNn15...',
    '................',
    '................',
    '................',
    '................',
    '...eeeeeeee5....',
    '...DDCCCCDDC5...',
    '...DDCCCCDDC5...',
    '...1nNNNNn15....',
    '...CDDCCDDC5....',
    '...CDDCCDDC5....',
    '...5DDDDDD5.....',
    '...55555555.....',
 ]],
}

GRIDS['paladin'] = {
 'down': [raw(l) for l in [
    '.....333333.....',
    '...3yYY33YYy3...',
    '...3YYY33YYY3...',
    '...3Y333333Y3...',
    '...3Y333333Y3...',
    '...3YYY33YYY3...',
    '...3yYY33YYy3...',
    '...3111111113...',
    '..3oooooooooo3..',
    '.3yo3oooooo3oy3.',
    '.3yo3oyyyyo3oy3.',
    '..333oooooo333..',
    '....3oyWWyo3....',
    '....3oooooo3....',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '.....333333.....',
    '...3yYYYY33y3...',
    '...3YYYYY33Y3...',
    '...3YYYYY33Y3...',
    '...3YYYYY33Y3...',
    '...3YYYYY33Y3...',
    '...3yYYYY33y3...',
    '...3111111113...',
    '..3ooooooooo3...',
    '..3yo3oooooo3...',
    '..3yo3oyyyyo3...',
    '...333oooooo3...',
    '.....3oyWWyo3...',
    '.....3oooooo3...',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '.....333333.....',
    '...3yYYYYYYy3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3yYYYYYYy3...',
    '...3111111113...',
    '..3oooooooooo3..',
    '.3yo3oooooo3oy3.',
    '.3yo3oooooo3oy3.',
    '..333oooooo333..',
    '....3oooooo3....',
    '....3oooooo3....',
    '................',
    '................',
 ]],
}

