# 주인공 — 인간 몸체 + 직업 킷 + HELD(손에 든 것).
# 배치: 0~3 머리/장비 · 4~6 얼굴(눈은 5행 5·6과 9·10열) · 7 목 · 8~15 몸
# 투구는 머리(4~11열)보다 한 칸 넓은 3~12열. 뺨가리개가 3~4열에 앉아 눈을 안 먹는다.
GRIDS = {}

GRIDS['human'] = {
 'down': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '....1nNMMNn1....',
    '....0haaaah0....',
    '....0wkaakw0....',
    '....0HhaahH0....',
    '.....00hh00.....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDDDDDDDDX...',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '....1nNMMNNn....',
    '....1nhaaaa0....',
    '....1nhwkaa0....',
    '....1nHhaah0....',
    '.....00hhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNX..',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDDDDDDDDX...',
    '....XDDDD1......',
    '....1nnnn1......',
 ]],
 'up': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '....1nNMMNn1....',
    '....1nNNNNn1....',
    '....1nNNNNn1....',
    '....1nnNNnn1....',
    '.....00hh00.....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDDDDDDDDX...',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
}

GRIDS['warrior'] = {
 'down': [raw(l) for l in [
    '.....222222.....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SS2222SS2...',
    '...2S......S2...',
    '...2S......S2...',
    '...2SS....SS2...',
    '....22222222....',
    '..2sSSSSSSSSs2..',
    '.2Ss2ssssss2sS2.',
    '.2Ss2sdddds2sS2.',
    '..222sdssds222..',
    '....2sdssds2....',
    '....2ddyydd2....',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '.....222222.....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SSSSSS22....',
    '...2SSSS........',
    '...2SSS.........',
    '...2SS..........',
    '....22222.......',
    '..2sSSSSSSSs2...',
    '..2Ss2ssssss2...',
    '..2Ss2sdddds2...',
    '...222sdssds2...',
    '.....2sdssds2...',
    '.....2ddyyd2....',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '.....222222.....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2dSSSSSSd2...',
    '....22222222....',
    '..2sSSSSSSSSs2..',
    '.2Ss2ssssss2sS2.',
    '.2Ss2ssssss2sS2.',
    '..222ssssss222..',
    '....2ssssss2....',
    '....2dddddd2....',
    '................',
    '................',
 ]],
}

GRIDS['mage'] = {
 'down': [raw(l) for l in [
    '........66......',
    '.......6bBb6....',
    '......6bBBb6....',
    '.....6bBBBb6....',
    '.663yyyyyyyy366.',
    '................',
    '................',
    '................',
    '................',
    '...6bBBBBBBb6...',
    '..6CCCCCCCCCC6..',
    '.6CDDCCCCCCDDC6.',
    '.63yyyyyyyyyy36.',
    '6CDDCCCCCCCCDDC6',
    '6CDDCCCCCCCCDDC6',
    '66CCCCCCCCCCCC66',
 ]],
 'side': [raw(l) for l in [
    '........66......',
    '.......6bBb6....',
    '......6bBBb6....',
    '.....6bBBBb6....',
    '.663yyyyyyyy366.',
    '................',
    '................',
    '................',
    '................',
    '...6bBBBBBBb6...',
    '..6CCCCCCCCCC6..',
    '.6CDDCCCCCCDDC6.',
    '.63yyyyyyyyyy36.',
    '6CDDCCCCCCCCDDC6',
    '6CDDCCCCCCCCDDC6',
    '66CCCCCCCCCCCC66',
 ]],
 'up': [raw(l) for l in [
    '........66......',
    '.......6bBb6....',
    '......6bBBb6....',
    '.....6bBBBb6....',
    '.663yyyyyyyy366.',
    '................',
    '................',
    '................',
    '................',
    '...6bBBBBBBb6...',
    '..6CCCCCCCCCC6..',
    '.6CDDCCCCCCDDC6.',
    '.6CDDDDDDDDDDC6.',
    '6CDDCCCCCCCCDDC6',
    '6CDDCCCCCCCCDDC6',
    '66CCCCCCCCCCCC66',
 ]],
}

GRIDS['priest'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..9CC3yyyy3CC9..',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9CDDDCCCCDDDC9.',
    '99CCCCCCCCCCCC99',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...9CC3yyCC9....',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9CDDDDDDDDC9..',
    '..99CCCCCCCC99..',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..9CCCCCCCCCC9..',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDDCCCCDDDC9.',
    '99CCCCCCCCCCCC99',
 ]],
}

GRIDS['rogue'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddk...',
    '.kCDDCCCCCCDD...',
    '.kCDDCCCCCCDD...',
    '..k1nNNNNNNn1...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddk...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk...',
    '..k1nNNNNNn1k...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddd...',
    '.kCDDCCCCCCDD...',
    '.kCDDCCCCCCDD...',
    '..k1nNNNNNNn1...',
    '..kCDDCCCCDDC...',
    '..kCDDCCCCDDC...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
}

GRIDS['ranger'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '............e...',
    '...51nNNNNn15...',
    '................',
    '................',
    '................',
    '................',
    '...eeeeeeee5....',
    '...DDCCCCDDC5...',
    '...DDCCCCDDC5...',
    '...1nNNNNn15....',
    '...CDDCCDDC5....',
    '...CDDCCDDC5....',
    '...5DDDDDD5.....',
    '...55555555.....',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '...e............',
    '...51nNNNNn15...',
    '................',
    '................',
    '................',
    '................',
    '...5eeeeeeee5...',
    '...5CDDCCCCDD...',
    '...5CDDCCCCDD...',
    '....51nNNNNn1...',
    '....5CDDCCDDC...',
    '....5CDDCCDDC...',
    '.....5DDDDDD5...',
    '.....55555555...',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '............e...',
    '...51nNNNNn15...',
    '................',
    '................',
    '................',
    '................',
    '...eeeeeeee5....',
    '...DDCCCCDDC5...',
    '...DDCCCCDDC5...',
    '...1nNNNNn15....',
    '...CDDCCDDC5....',
    '...CDDCCDDC5....',
    '...5DDDDDD5.....',
    '...55555555.....',
 ]],
}

GRIDS['paladin'] = {
 'down': [raw(l) for l in [
    '.....333333.....',
    '...3yYYYYYYy3...',
    '...3YYYYYYYY3...',
    '...3YYY33YYY3...',
    '...3Y333333Y3...',
    '...3Y333333Y3...',
    '...3YYY33YYY3...',
    '...3111111113...',
    '..3oooooooooo3..',
    '.3yo3oooooo3oy3.',
    '.3yo3oyyyyo3oy3.',
    '..333oooooo333..',
    '....3oyWWyo3....',
    '....3oooooo3....',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '.....333333.....',
    '...3yYYYYYYy3...',
    '...3YYYYYYYY3...',
    '...3YYYYY33Y3...',
    '...3YYYYY33Y3...',
    '...3YYYYY33Y3...',
    '...3YYYYY33Y3...',
    '...311111111....',
    '..3ooooooooo3...',
    '..3yo3oooooo3...',
    '..3yo3oyyyyo3...',
    '...333oooooo3...',
    '.....3oyWWyo3...',
    '.....3oooooo3...',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '.....333333.....',
    '...3yYYYYYYy3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3yYYYYYYy3...',
    '...3111111113...',
    '..3oooooooooo3..',
    '.3yo3oooooo3oy3.',
    '.3yo3oooooo3oy3.',
    '..333oooooo333..',
    '....3oooooo3....',
    '....3oooooo3....',
    '................',
    '................',
 ]],
}

