# 인간 몸체 + 전사 킷, 3방향. src/pixels.js 최종본.
# 기준: tools/style-level.png (오크). 문법은 SPRITES.md 1절.
GRIDS = {}

GRIDS['human'] = {
 'down': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nNNNNn1....',
    '...1nNNNNNNn1...',
    '...0haaaaaah0...',
    '...0hwkaakwh0...',
    '...0haaaaaah0...',
    '...0HhaaaahH0...',
    '....00hhhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nNNNNn1....',
    '...1nNNNNNNn1...',
    '...1nNhaaaaa0...',
    '...1nhwkaaaa0...',
    '...1nhaaaaaa0...',
    '...1nHhaaaah0...',
    '....00hhhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNX..',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '....XDDDD1......',
    '....1nnnn1......',
 ]],
 'up': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nNNNNn1....',
    '...1nNNNNNNn1...',
    '...1nNNNNNNn1...',
    '...1nNNNNNNn1...',
    '...1nNNNNNNn1...',
    '...1nnNNNNnn1...',
    '....00hhhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
}

GRIDS['warrior'] = {
 'down': [raw(l) for l in [
    '................',
    '.....222222.....',
    '....2dSSSSd2....',
    '...2dSSSSSSd2...',
    '...2SS2..2SS2...',
    '...2S......S2...',
    '...2S......S2...',
    '................',
    '................',
    '..2sSSSSSSSSs2..',
    '.2sSSCCCCCCSSs2.',
    '................',
    '................',
    '..2ssssssssss2..',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '................',
    '.....222222.....',
    '....2dSSSSd2....',
    '...2dSSSSSSd2...',
    '...2SS2..2SS2...',
    '...2S......S2...',
    '...2S......S2...',
    '................',
    '................',
    '..2sSSSSSSSSs2..',
    '.2sSSCCCCCCSSs2.',
    '................',
    '................',
    '..2ssssssssss2..',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '................',
    '.....222222.....',
    '....2dSSSSd2....',
    '...2dSSSSSSd2...',
    '...2dSSSSSSd2...',
    '...2S......S2...',
    '................',
    '................',
    '................',
    '..2sSSSSSSSSs2..',
    '.2sSSCCCCCCSSs2.',
    '................',
    '................',
    '..2ssssssssss2..',
    '................',
    '................',
 ]],
}

