# 주인공 — 인간 몸체 + 직업 킷 6종, 각 3방향. src/pixels.js 최종본.
# 머리 장비는 직업마다 다르고 방향마다 따로 그린다.
#   정면 가운데가 열려 눈이 보임 / 옆 앞쪽이 열리고 뒤통수가 길다 / 뒤 열린 곳 없음
GRIDS = {}

GRIDS['human'] = {
 'down': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '...1nNMNNMNn1...',
    '...1nhaaaahn1...',
    '...1nwkaakwn1...',
    '...0haaaaaah0...',
    '...0HhaaaahH0...',
    '....00hhhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '......1111......',
    '.....1nnNNn1....',
    '....1nNMNNMn1...',
    '....1nNhaaaa0...',
    '....1nhwkaaa0...',
    '....1nhaaaaa0...',
    '....1nHhaaah0...',
    '.....00hhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNX..',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '....XDDDD1......',
    '....1nnnn1......',
 ]],
 'up': [raw(l) for l in [
    '................',
    '.....111111.....',
    '....1nnNNnn1....',
    '...1nNMNNMNn1...',
    '...1nNNNNNNn1...',
    '...1nNNNNNNn1...',
    '...1nNNNNNNn1...',
    '...1nnNNNNnn1...',
    '....00hhhh00....',
    '..XCCDDCCDDCCX..',
    '.XCNDDCCCCDDNCX.',
    '.XhNDDCCCCDDNhX.',
    '..XCNDDCCDDNCX..',
    '..1nNNNNNNNNn1..',
    '...XDD1..1DDX...',
    '...1nn1..1nn1...',
 ]],
}

GRIDS['warrior'] = {
 'down': [raw(l) for l in [
    '.....222222.....',
    '....2dSSSSd2....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SS2222SS2...',
    '...2S......S2...',
    '...2S......S2...',
    '...2SS....SS2...',
    '....22222222....',
    '.2Ss2ssssss2sS2.',
    '.2Ss2sdddds2sS2.',
    '..222sdssds222..',
    '....2sdssds2....',
    '....2ddyydd2....',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '....222222......',
    '...2dSSSSd22....',
    '..2dSSSSSSSd2...',
    '..2dSSSSSSSS2...',
    '..2dSSSSS222....',
    '..2dSSSS........',
    '..2dSSS.........',
    '..2dSS..........',
    '..2222222.......',
    '..2Ss2sssss2....',
    '..2Ss2sdddss2...',
    '...222sdssds2...',
    '.....2sdssds2...',
    '.....2ddyyd2....',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '.....222222.....',
    '....2dSSSSd2....',
    '...2dSSSSSSd2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2SSSSSSSS2...',
    '...2dSSSSSSd2...',
    '....22222222....',
    '.2Ss2ssssss2sS2.',
    '.2Ss2ssssss2sS2.',
    '..222ssssss222..',
    '....2ssssss2....',
    '....2dddddd2....',
    '................',
    '................',
 ]],
}

GRIDS['mage'] = {
 'down': [raw(l) for l in [
    '.......66.......',
    '......6bb6......',
    '.....6bBBb6.....',
    '....6bBBBBb6....',
    '.66bBBBBBBBBb66.',
    '................',
    '................',
    '.............1M1',
    '..6bBBBBb6...1M1',
    '..6CCCCCCC6..1M1',
    '.6CDDCCCDDC6.1M1',
    '.63yyyyyyy36.1M1',
    '6CDDCCCCCDDC61M1',
    '6CDDCCCCCDDC61M1',
    '6CDDDCCCDDDC6111',
    '66CCCCCCCCC66...',
 ]],
 'side': [raw(l) for l in [
    '.......66.......',
    '......6bb6......',
    '.....6bBBb6.....',
    '....6bBBBBb6....',
    '.66bBBBBBBBBb66.',
    '................',
    '................',
    '1M1.............',
    '1M1..6bBBBBb6...',
    '1M1.6CCCCCCC6...',
    '1M16CDDCCCDDC6..',
    '1M163yyyyyyy36..',
    '1M16CDDCCCDDC6..',
    '1M16CDDCCCDDC6..',
    '1116CDDDCCDDC6..',
    '...66CCCCCCC66..',
 ]],
 'up': [raw(l) for l in [
    '.......66.......',
    '......6bb6......',
    '.....6bBBb6.....',
    '....6bBBBBb6....',
    '.66bBBBBBBBBb66.',
    '................',
    '................',
    '.............1M1',
    '..6bBBBBb6...1M1',
    '..6CCCCCCC6..1M1',
    '.6CDDCCCDDC6.1M1',
    '.6CDDDDDDDC6.1M1',
    '6CDDCCCCCDDC61M1',
    '6CDDCCCCCDDC61M1',
    '6CDDDCCCDDDC6111',
    '66CCCCCCCCC66...',
 ]],
}

GRIDS['priest'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..9CC3yyyy3CC9..',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9C3yyCCCCyy3C9.',
    '.9CDDDCCCCDDDC9.',
    '99CCCCCCCCCCCC99',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '...9CC3yyCC9....',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9C3yyCCyy3C9..',
    '..9CDDDDDDDDC9..',
    '..99CCCCCCCC99..',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..9CCCCCCCCCC9..',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDCCCCCCDDC9.',
    '.9CDDDCCCCDDDC9.',
    '99CCCCCCCCCCCC99',
 ]],
}

GRIDS['rogue'] = {
 'down': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddk...',
    '.kCDDCCCCCCDDk..',
    '.kCDDCCCCCCDDk..',
    '..k1nNNNNNNn1k..',
    '..kCDDCCCCDDk2S.',
    '..kCDDCCCCDDk2S.',
    '...kDDDDDDDDk1M.',
    '...kkkkkkkkkk...',
 ]],
 'side': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kdddddddddk...',
    '..kCDDCCCCDDk...',
    '..kCDDCCCCDDk2S.',
    '..k1nNNNNNn1k2S.',
    '..kCDDCCCCDDk1M.',
    '..kCDDCCCCDDk...',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
 'up': [raw(l) for l in [
    '................',
    '................',
    '................',
    '...kddddddddk...',
    '................',
    '................',
    '................',
    '................',
    '..kddddddddddk..',
    '.kCDDCCCCCCDDCk.',
    '.kCDDCCCCCCDDCk.',
    '..k1nNNNNNNn1k..',
    '..kCDDCCCCDDCk..',
    '..kCDDCCCCDDCk..',
    '...kDDDDDDDDk...',
    '...kkkkkkkkkk...',
 ]],
}

GRIDS['ranger'] = {
 'down': [raw(l) for l in [
    '................',
    '.............FF.',
    '............eFF.',
    '...51nNNNNn15e..',
    '................',
    '................',
    '................',
    '.............3y.',
    '..5eeeeeeee5.3y.',
    '.5CDDCCCCDDC51N1',
    '.5CDDCCCCDDC51N1',
    '..51nNNNNn15.1N1',
    '..5CDDCCDDC5.1N1',
    '..5CDDCCDDC5.111',
    '...5DDDDDD5.....',
    '...55555555.....',
 ]],
 'side': [raw(l) for l in [
    '................',
    '.FF.............',
    '.FFe............',
    '..e51nNNNNn15...',
    '................',
    '................',
    '................',
    '.3y.............',
    '.3y5eeeeeeee5...',
    '1N15CDDCCCCDDC5.',
    '1N15CDDCCCCDDC5.',
    '1N1.51nNNNNn15..',
    '1N1.5CDDCCDDC5..',
    '111.5CDDCCDDC5..',
    '.....5DDDDDD5...',
    '.....55555555...',
 ]],
 'up': [raw(l) for l in [
    '................',
    '.............FF.',
    '............eFF.',
    '...51nNNNNn15e..',
    '................',
    '................',
    '................',
    '.............3y.',
    '..5eeeeeeee5.3y.',
    '.5CDDCCCCDDC51N1',
    '.5CDDCCCCDDC51N1',
    '..51nNNNNn15.1N1',
    '..5CDDCCDDC5.1N1',
    '..5CDDCCDDC5.111',
    '...5DDDDDD5.....',
    '...55555555.....',
 ]],
}

GRIDS['paladin'] = {
 'down': [raw(l) for l in [
    '......4RR4......',
    '....34RRRR43....',
    '...3yYYYYYYy3...',
    '...3YYYYYYYY3...',
    '...3YYooooYY3...',
    '...3Y......Y3...',
    '...3Y......Y3...',
    '...3Yo....oY3...',
    '....3oooooo3....',
    '.3Yo3yyyyyy3oY3.',
    '.3Yo3yooooy3oY3.',
    '..333yyyyyy333..',
    '....3yoWWoy3....',
    '....3yooooy3....',
    '................',
    '................',
 ]],
 'side': [raw(l) for l in [
    '....4RRR4.......',
    '..34RRRRR43.....',
    '..3yYYYYYYy3....',
    '..3YYYYYYYY3....',
    '..3YYYYYoo3.....',
    '..3YYYY.........',
    '..3YYY..........',
    '..3Yo...........',
    '..3ooooo........',
    '..3Yo3yyyyy3....',
    '..3Yo3yooy3o3...',
    '...333yyyyy3....',
    '.....3yoWoy3....',
    '.....3yooy33....',
    '................',
    '................',
 ]],
 'up': [raw(l) for l in [
    '......4RR4......',
    '....34RRRR43....',
    '...3yYYYYYYy3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3YYYYYYYY3...',
    '...3yYoooYYy3...',
    '....3oooooo3....',
    '.3Yo3yyyyyy3oY3.',
    '.3Yo3yyyyyy3oY3.',
    '..333yyyyyy333..',
    '....3yooooy3....',
    '....3yooooy3....',
    '................',
    '................',
 ]],
}

